Curso/urls.py
from django.urls import path

from Curso import views

urlpatterns = [
    path('', views.CursoView, name='curso'),
    
    path('cursos/consulta', views.CM_cursoListView.as_view(), name='cm_curso-list'),
    path('cursos/consulta/<int:cm_curso_id>/curso_oferta', views.curso_ofertaView, name='curso_oferta'),
    path('cursos/cadastro', views.CM_cursoCreate.as_view(), name='cm_curso-create'),
    path('cursos/<int:pk>', views.CM_cursoDetailView.as_view(), name='cm_curso-detail'),
    path('cursos/<int:pk>/editar', views.CM_cursoUpdateView.as_view(), name='cm_curso-update'),
    path('cursos/<int:pk>/excluir', views.CM_cursoDeleteView.as_view(), name='cm_curso-delete'),
    
    path('ofertas/consulta', views.SI_curso_ofertaListView.as_view(), name='si_curso_oferta-list'),
    path('ofertas/cadastro', views.SI_curso_ofertaCreate, name='si_curso_oferta-create'),
    path('ofertas/<int:pk>', views.SI_curso_ofertaDetailView.as_view(), name='si_curso_oferta-detail'),
    path('ofertas/<int:si_curso_oferta_id>/editar', views.SI_curso_ofertaUpdateView, name='si_curso_oferta-update'),
    path('ofertas/<int:pk>/excluir', views.SI_curso_ofertaDeleteView.as_view(), name='si_curso_oferta-delete'),
]

Polo/urls.py
from django.urls import path

from Polo import views

urlpatterns = [
    path('', views.PoloView, name='polo'),
    
    path('polos/consulta', views.CM_poloListView.as_view(), name='cm_polo-list'),
    path('polos/cadastro', views.CM_poloCreate.as_view(), name='cm_polo-create'),
    path('polos/<int:pk>/editar', views.CM_poloUpdateView.as_view(), name='cm_polo-update'),
    path('polos/<int:pk>/excluir', views.CM_poloDeleteView.as_view(), name='cm_polo-delete'),
    path('polos/<int:pk>/associarPoloIes', views.SI_associa_polo_iesUpdate.as_view(), name='si_associa_polo_ies-update'),
    
    path('ies/consulta', views.SI_iesListView.as_view(), name='si_ies-list'),
    path('ies/cadastro', views.SI_iesCreate.as_view(), name='si_ies-create'),
    path('ies/<int:pk>/editar', views.SI_iesUpdateView.as_view(), name='si_ies-update'),
    path('ies/<int:pk>/excluir', views.SI_iesDeleteView.as_view(), name='si_ies-delete'),
    
    path('mantenedor/consulta', views.SI_mantenedorListView.as_view(), name='si_mantenedor-list'),
    path('mantenedor/cadastro', views.SI_mantenedorCreate.as_view(), name='si_mantenedor-create'),
    path('mantenedor/<int:pk>/editar', views.SI_mantenedorUpdateView.as_view(), name='si_mantenedor-update'),
    path('mantenedor/<int:pk>/excluir', views.SI_mantenedorDeleteView.as_view(), name='si_mantenedor-delete'),
]

proceg/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
# from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('procead/', include('procead.urls')),
    path('curso/', include('Curso.urls')),
    path('polo/', include('Polo.urls')),
    path('financeiro/', include('Financeiro.urls')),
    path('viagem/', include('Viagens.urls')),
    path('administracao/', include('Acesso_Restrito.urls')),
    path('curso/', include('Curso.urls')),
    path('almoxarifado/', include('Almoxarifado.urls')),
    path('ticket/', include('Ticket.urls')),
    path('', RedirectView.as_view(url='procead/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    ### Add Django site authentication urls (for login, logout, password management)
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

Curso/models.py
from Acesso_Restrito.models import CM_pessoa
from Polo.models import CM_polo

from procead.imports import *

from django.contrib.auth.models import User

from procead.validators import validate_edital_year, validate_is_zero_or_positive, validate_positive

# Create your models here.
class SI_tipo_curso(models.Model):
    nome = models.CharField(max_length=45)
    
    class Meta:
        verbose_name = 'SI - Tipo de Curso'
        verbose_name_plural = 'SI - Tipos de Curso'
        
    def __str__(self):
        return self.nome

class SI_curso_projeto(models.Model):
    nome = models.CharField(max_length=45)
    denominacao_programa = models.CharField(max_length=500)
    sigla_programa = models.CharField(max_length=20)
    denominacao_secretaria = models.CharField(max_length=500)
    sigla_secretaria = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = 'SI - Curso-Projeto'
        verbose_name_plural = 'SI - Cursos-Projetos'
        
    def __str__(self):
        return self.nome

class SI_curso_situacao(models.Model):
    nome = models.CharField(max_length=45)
    
    class Meta:
        verbose_name = 'SI - Curso Situação'
        verbose_name_plural = 'SI - Cursos Situação'
        
    def __str__(self):
        return self.nome

class FI_orgao_fomento(models.Model):
    nome = models.CharField(max_length=200)
    
    class Meta:
        verbose_name = 'FI - Orgão de Fomento'
        verbose_name_plural = 'FI - Orgãos de Fomento'
        
    def __str__(self):
        return self.nome

class FI_fonte_pagadora(models.Model):
    nome = models.CharField(max_length=200)
    sigla = models.CharField(max_length=50, null=True, blank=True)
    orgao_fomento = models.ForeignKey(FI_orgao_fomento, on_delete=models.RESTRICT)
    
    class Meta:
        verbose_name = 'FI - Fonte Pagadora'
        verbose_name_plural = 'FI - Fontes Pagadoras'
        
    def __str__(self):
        return self.nome

class FI_programa(models.Model):
    nome = models.CharField(max_length=200)
    sigla = models.CharField(max_length=50, null=True, blank=True)
    fonte_pagadora = models.ForeignKey(FI_fonte_pagadora, on_delete=models.RESTRICT)
    
    class Meta:
        verbose_name = 'FI - Programa'
        
    def __str__(self):
        return self.nome

class CM_curso(models.Model):
    OPCOES_STATUS = (
        ('a', 'Ativo'),
        ('i', 'Inativo'),
    )
    
    nome = models.CharField(max_length=200)
    sigla = models.CharField(max_length=10, null=True, blank=True)
    departamento = models.CharField(max_length=100, null=True, blank=True)
    unidade = models.CharField(max_length=100, null=True, blank=True)
    tipo_curso = models.ForeignKey(SI_tipo_curso, on_delete=models.RESTRICT, verbose_name="Tipo")
    programa = models.ForeignKey(FI_programa, on_delete=models.RESTRICT)
    curso_situacao = models.ForeignKey(SI_curso_situacao, on_delete=models.RESTRICT, verbose_name="Situação")
    duracao_esperada = models.PositiveIntegerField(null=True, blank=True, verbose_name="Duração esperada", help_text="(meses)", validators=[validate_positive])
    email = models.EmailField(verbose_name="E-mail")
    telefone = models.CharField(max_length=20, null=True, blank=True, verbose_name="Telefone")
    coordenador = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    status = models.CharField(max_length=1, choices=OPCOES_STATUS)
    descricao = models.TextField(max_length=2000, verbose_name="Descrição/Apresentação")
    perfil_egresso = models.TextField(max_length=2000, verbose_name="Perfil do Egresso")
    
    ## Abaixo, campos que não estão no sistema atual
    # curso_projeto = models.ForeignKey(SI_curso_projeto, on_delete=models.RESTRICT, null=True, blank=True)
    # tipo_bolsa = models.CharField(max_length=4, null=True, blank=True)
    # chamada_uab = models.CharField(max_length=45, null=True, blank=True)
    # data_inicio = models.DateField(null=True, blank=True)
    
    class Meta:
        verbose_name = 'CM - Curso'
    
    def __str__(self):
        return self.nome
        
    def get_absolute_url(self):
        return reverse('cm_curso-list')
        
class SI_curso_oferta(models.Model):
    curso = models.ForeignKey(CM_curso, on_delete=models.RESTRICT)
    numero_oferta = models.PositiveIntegerField(verbose_name="Número da Oferta", validators=[validate_is_zero_or_positive])
    data_inicio = models.DateField(verbose_name="Data de início", help_text="(Data do SISUAB que possibilita cálculo e geração da planilha)")
    data_fim = models.DateField(verbose_name="Data de término prevista")
    periodos = models.PositiveIntegerField(verbose_name="Quantidade de Períodos", validators=[validate_positive])
    num_vagas = models.PositiveIntegerField(verbose_name="Número de Vagas", validators=[validate_is_zero_or_positive], default=0, help_text="(Cadastrar através da aba Vincular Oferta/Polo)")
    polos_vinculados = models.ManyToManyField(CM_polo, through='SI_associa_curso_oferta_polo')
    
    class Meta:
        verbose_name = 'SI - Curso-Oferta'
        verbose_name_plural = 'SI - Cursos-Ofertas'
        
    def __str__(self):
        return str(self.numero_oferta) + 'ª/' + str(self.data_inicio.year) + ": " + str(self.curso)
      
class SI_associa_curso_oferta_polo(models.Model):
    oferta = models.ForeignKey(SI_curso_oferta, on_delete=models.CASCADE)
    polo = models.ForeignKey(CM_polo, on_delete=models.RESTRICT)
    num_vagas = models.PositiveIntegerField(verbose_name="Número de vagas", validators=[validate_positive])
    
    class Meta:
        verbose_name = 'SI - Curso-Oferta-Polo'
        verbose_name_plural = 'SI - Cursos-Ofertas-Polos'
        
    def get_absolute_url(self):
        return reverse('si_curso_oferta-list')
    
    def __str__(self):
        return self.oferta.curso.nome + " - Polo: " + self.polo.nome + " - Vagas: " + str(self.num_vagas)


## Edital
class Edital(models.Model):
    numero = models.PositiveIntegerField(primary_key=True)
    curso = models.ForeignKey(CM_curso, on_delete=models.RESTRICT)
    descricao = models.TextField()
    data_cadastro = models.DateTimeField(auto_now_add=True)

class Vaga(models.Model):
    edital = models.ForeignKey(Edital, on_delete=models.RESTRICT)
    descricao = models.TextField()
    quantidade = models.PositiveIntegerField()
    data_inicio_inscricao = models.DateTimeField()
    data_fim_inscricao = models.DateTimeField()
    data_inicio_validacao = models.DateTimeField()
    data_fim_validacao = models.DateTimeField()
    polo = models.ForeignKey(CM_polo, on_delete=models.RESTRICT)

class InscricaoVaga(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)

class ValidacaoVaga(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)

class ConfirmacaoVaga(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    confirmado = models.BooleanField()

class JustificativaVaga(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    descricao = models.CharField(max_length=255)

class AprovacaoVaga(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    aprovado = models.BooleanField()

class DescricaoCampo(models.Model):
    descricao = models.CharField(max_length=127)

class Campo(models.Model):
    descricao_campo = models.ForeignKey(DescricaoCampo, on_delete=models.RESTRICT)
    vaga = models.ForeignKey(Vaga, on_delete=models.RESTRICT)
    peso = models.FloatField()
    pontuacao_maxima = models.FloatField()
    data_inicio = models.DateField()
    data_fim = models.DateField()
    obrigatorio = models.BooleanField()
    upload = models.BooleanField()

class InscricaoVagaCampo(models.Model):
    inscricao_vaga = models.ForeignKey(InscricaoVaga, on_delete=models.RESTRICT)
    campo = models.ForeignKey(Campo, on_delete=models.RESTRICT)
    pontuacao = models.FloatField()

class DocumentacaoInscricaoVagaCampo(models.Model):
    inscricao_vaga = models.ForeignKey(InscricaoVaga, on_delete=models.RESTRICT)
    campo = models.ForeignKey(Campo, on_delete=models.RESTRICT)
    documentacao = models.FileField()

Curso/forms.py
import datetime
from django import forms
from Acesso_Restrito.models import CM_cidade

from Curso.models import SI_associa_curso_oferta_polo, SI_curso_oferta

class CM_cidadeForm(forms.ModelForm):
    class Meta:
        model = CM_cidade
        fields = '__all__'

class SI_curso_ofertaForm(forms.ModelForm):
    class Meta:
        model = SI_curso_oferta
        fields = [
            'curso',
            'numero_oferta',
            'data_inicio',
            'data_fim',
            'periodos'
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['data_inicio'].widget.attrs['class'] = 'maskedDate'
        self.fields['data_fim'].widget.attrs['class'] = 'maskedDate'
        
class SI_associa_curso_oferta_poloForm(forms.ModelForm):
    class Meta:
        model = SI_associa_curso_oferta_polo
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['polo'].widget.attrs['required'] = ''
        self.fields['num_vagas'].widget.attrs['required'] = ''

Curso/templates/Curso/cm_curso_delete.html
{% extends "base_generic.html" %}

{% block content %}


{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Cursos" %}
    
{% include "includes/delete_form.html" with title="Cursos" divider="curso" name_url=cm_curso %}

{% endblock %}

Curso/templates/Curso/cm_curso_detail.html
{% extends "base_generic.html" %}

{% block content %}

{% endblock %}

Curso/templates/Curso/cm_curso_form.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Cursos" %}

<div class="container mt-5">
    
    {% include "includes/create_header.html" with title="Cursos" divider="curso" list_url="cm_curso-list" %}

    <form method="post">{% csrf_token %}
        <table class="table table">
            <tr>
                <td colspan="3">{{form.nome.label}}{{form.nome}}</td>
                <td>{{form.sigla.label}}{{form.sigla}}</td>
            </tr>
            <tr>
                <td colspan="3">{{form.departamento.label}}{{form.departamento}}</td>
                <td>{{form.unidade.label}}{{form.unidade}}</td>
            </tr>
            <tr>
                <td colspan="4">{{form.coordenador.label}}{{form.coordenador}}</td>
            </tr>
            <tr>
                <td colspan="3">{{form.email.label}}{{form.email}}</td>
                <td>{{form.telefone.label}}{{form.telefone}}</td>
            </tr>
            <tr>
                <td>{{form.tipo_curso.label}}{{form.tipo_curso}}</td>
                <td>{{form.programa.label}}{{form.programa}}</td>
                <td>{{form.curso_situacao.label}}{{form.curso_situacao}}</td>
                <td>{{form.duracao_esperada.label}}{{form.duracao_esperada}}</td>
            </tr>
            <tr>
                <td colspan="2">{{form.descricao.label}}: {{form.descricao}}</td>
                <td colspan="2">{{form.perfil_egresso.label}}: {{form.perfil_egresso}}</td>
            </tr>
            <tr>
                <td>{{form.status.label}}{{form.status}}</td>
                <td colspan="3"></td>
            </tr>
        </table>
        {% include "includes/submit_button.html" with action="Enviar" %}
    </form>
</div>

<!-- Script para transformar o select em questão em Select2 -->    
<script>
    $(function() {
        $('#id_coordenador').select2();
    });
</script>

{% endblock %}

Curso/templates/Curso/cm_curso_list.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Cursos" %}

<div class="container">
    {% include "includes/list_header.html" with title="Cursos" divider="curso" create_url="cm_curso-create" %}
    
    <div class="border-left border-right border-bottom">
        {% include "includes/list_filter.html" with filter_name=cm_curso_filter.form.nome %}
        
        {% if cm_curso_list %}
        <table id="list-table" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th class="text-center">Ofertas</th>
                    <th class="text-center">Editar</th>
                    <th class="text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>
                {% for cm_curso in page_obj %}
                <tr>
                    <td>{{cm_curso.nome}}</td>
                    <td>{{cm_curso.email}}</td>
                    <td class="text-center">
                        <a href="" data-bs-toggle="modal" data-bs-target="#cursoModal{{cm_curso.id}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'cm_curso-update' cm_curso.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ee844b" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'cm_curso-delete' cm_curso.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ae1f25" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
                            </svg>
                        </a>
                    </td>
                </tr>

                <!-- Modal contendo as informações do polo -->
                <div id="cursoModal{{cm_curso.id}}" class="modal fade" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                  
                      <!-- Conteúdo do modal-->
                      <div class="modal-content">
                        <div class="bg-curso modal-header">
                            <h4 class="text-light modal-title">Ofertas para o curso <strong>{{ cm_curso.nome }}</strong></h4>
                        </div>
                        <div class="modal-body">
                            {% if cm_curso.si_curso_oferta_set.all %}
                            {% for oferta in cm_curso.si_curso_oferta_set.all %}
                                <p><strong>Oferta: </strong>{{oferta.numero_oferta}}ª/{{oferta.data_inicio|date:"Y"}}</p>
                                <p><strong>Número total de vagas: </strong>{{oferta.num_vagas}}</p> 
                                <p><strong>Data de início: </strong>{{oferta.data_inicio}}</p>
                                <p><strong>Data de fim: </strong>{{oferta.data_fim}}</p>
                                <p><strong>Polos: </strong></p>
                                <ul>
                                {% for associacao in oferta.si_associa_curso_oferta_polo_set.all %}
                                    <li>{{associacao.polo.nome}}: {{associacao.num_vagas}} vaga(s)</li>
                                {% endfor %}
                                </ul>
                                <hr>
                            {% endfor %}
                            {% else %}
                                <p>Não existem ofertas vinculadas a esse curso</p>
                            {% endif %}
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                        </div>
                      </div>
                  
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>

        {% include "includes/pagination.html" %}
        
        {% else %}
        <p class="ml-1 mt-3">Não há cursos cadastradas no sistema</p>
        {% endif %}
        
    </div>
</div>
{% endblock %}

Curso/templates/Curso/cm_curso_update.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Cursos" %}

{% include "includes/update_form.html" with title="Cursos" divider="curso" name=cm_curso.nome %}

{% endblock %}

Curso/templates/Curso/curso.html
{% extends "base_generic.html" %}

{% block content %}
<main>
    
    {% include "includes/breadcrumb.html" with level=2 current_page="Curso" %}

    {% comment %} {% include "includes/submenu.html" with submenus=3 color="bg-curso" url1="cm_curso-list" page1="Cursos" url2="si_curso_oferta-list" page2="Ofertas" url3="pr_edital-list" page3="Editais" %} {% endcomment %}
    {% include "includes/submenu.html" with url1="cm_curso-list" page1="Cursos" url2="si_curso_oferta-list" page2="Ofertas" url3="pr_edital-list" page3="Editais" %}

</main>
{% endblock %}

Curso/templates/Curso/si_curso_oferta_detail.html
{% extends "base_generic.html" %}

{% block content %}

{% endblock %}

Curso/templates/Curso/si_curso_oferta_form.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Ofertas" %}

<div class="container">
    
    {% include "includes/create_header.html" with title="Ofertas" divider="curso" list_url="si_curso_oferta-list" %}
    
    {% include "includes/messages.html" %}

    <form method="post" action="">{% csrf_token %}
        <table class="table table-hover table-striped">
            <tr>
                <th>{{form.curso.label}}</th>
                <td>{{form.curso}}</td>
            </tr>
            <tr>
                <th>{{form.numero_oferta.label}}</th>
                <td class="d-flex">{{form.numero_oferta}}/{{form.ano_oferta}}</td>
            </tr>
            <tr>
                <th>{{form.data_inicio.label}}</th>
                <td>{{form.data_inicio}}</td>
            </tr>
            <tr>
                <th>{{form.data_fim.label}}</th>
                <td>{{form.data_fim}}</td>
            </tr>
            <tr>
                <th>{{form.periodos.label}}</th>
                <td>{{form.periodos}}</td>
            </tr>
        </table>
        {{ form_si_associa_curso_oferta_polo.management_form }}    
        {% for extra_form in form_si_associa_curso_oferta_polo %}
        <div class="inlineForm" style="display: flex;">
            <span class="label">{{ extra_form.polo.label }}</span>
            <span class="poloSelect">{{ extra_form.polo }}</span>
            <span class="label">{{ extra_form.num_vagas.label }}</span>
            <span class="num_vagasSelect">{{ extra_form.num_vagas }}</span>
        </div>
        {% endfor %}
        <br>
        
        {% include "includes/submit_button.html" with action="Cadastrar" %}

    </form>
</div>

<script>
    $(function() {
        $('.inlineForm').formset({
            prefix: '{{ form_si_associa_curso_oferta_polo.prefix }}',
            addText: 'Adicionar Polo',
            deleteText: 'Remover Polo'
        });
        $('#id_curso').select2();
    })
</script>

{% endblock %}

Curso/templates/Curso/si_curso_oferta_update.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="curso" page2="Curso" current_page="Ofertas" %}

<div class="container">
    <h3 class="h3">Ofertas</h3>

    <div class="divider-curso mb-2"></div>

    <h4 class="h4">Oferta <strong>{{oferta}}</strong></h4>

    <form method="post" action="">{% csrf_token %}
        <table class="table table-hover table-striped">
            {{ form.as_table }}
        </table>
        {{ form_si_associa_curso_oferta_polo.management_form }}
        
        {% for extra_form in form_si_associa_curso_oferta_polo %}
        
        {% for hidden in extra_form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        
        <div class="inlineForm" style="display: flex;">
            <span class="label">{{ extra_form.polo.label }}</span>
            <span class="poloSelect">{{ extra_form.polo }}</span>
            <span class="label">{{ extra_form.num_vagas.label }}</span>
            <span class="num_vagasSelect">{{ extra_form.num_vagas }}</span>
        </div>
        {% endfor %}
        <br>
        
        {% include "includes/submit_button.html" with action="Atualizar" %}

    </form>
</div>

<script type="text/javascript">
    $(function() {
        $('.inlineForm').formset({
            prefix: '{{ form_si_associa_curso_oferta_polo.prefix }}',
            addText: 'Adicionar Polo',
            deleteText: 'Remover Polo'
        });
        $('#id_curso').select2();
        $('#id_numero_oferta').val({{instancia.oferta|stringformat:"i"|slice:"4:7"}});
        $('#id_ano_oferta').val({{instancia.oferta|stringformat:"i"|slice:"0:4"}});
    })
</script>

{% endblock content %}