Polo/urls.py
from django.urls import path

from Polo import views

urlpatterns = [
    path('', views.PoloView, name='polo'),
    
    path('polos/consulta', views.CM_poloListView.as_view(), name='cm_polo-list'),
    path('polos/cadastro', views.CM_poloCreate.as_view(), name='cm_polo-create'),
    path('polos/<int:pk>/editar', views.CM_poloUpdateView.as_view(), name='cm_polo-update'),
    path('polos/<int:pk>/excluir', views.CM_poloDeleteView.as_view(), name='cm_polo-delete'),
    path('polos/<int:pk>/associarPoloIes', views.SI_associa_polo_iesUpdate.as_view(), name='si_associa_polo_ies-update'),
    
    path('ies/consulta', views.SI_iesListView.as_view(), name='si_ies-list'),
    path('ies/cadastro', views.SI_iesCreate.as_view(), name='si_ies-create'),
    path('ies/<int:pk>/editar', views.SI_iesUpdateView.as_view(), name='si_ies-update'),
    path('ies/<int:pk>/excluir', views.SI_iesDeleteView.as_view(), name='si_ies-delete'),
    
    path('mantenedor/consulta', views.SI_mantenedorListView.as_view(), name='si_mantenedor-list'),
    path('mantenedor/cadastro', views.SI_mantenedorCreate.as_view(), name='si_mantenedor-create'),
    path('mantenedor/<int:pk>/editar', views.SI_mantenedorUpdateView.as_view(), name='si_mantenedor-update'),
    path('mantenedor/<int:pk>/excluir', views.SI_mantenedorDeleteView.as_view(), name='si_mantenedor-delete'),
]

proceg/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
# from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('procead/', include('procead.urls')),
    path('curso/', include('Curso.urls')),
    path('polo/', include('Polo.urls')),
    path('financeiro/', include('Financeiro.urls')),
    path('viagem/', include('Viagens.urls')),
    path('administracao/', include('Acesso_Restrito.urls')),
    path('curso/', include('Curso.urls')),
    path('almoxarifado/', include('Almoxarifado.urls')),
    path('ticket/', include('Ticket.urls')),
    path('', RedirectView.as_view(url='procead/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    ### Add Django site authentication urls (for login, logout, password management)
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

Polo/models.py
from tabnanny import verbose
from Acesso_Restrito.models import CM_pais, CM_pessoa
from procead.imports import *

from django.db import models

from localflavor.br.models import BRPostalCodeField, BRCNPJField

from procead.validators import validate_is_zero_or_positive, validate_national_phone_number, validate_positive

# Create your models here.
class SI_mantenedor(models.Model):
    """Armazena mantenedores: provedores de recursos para manutenção dos polos
    """
    # Opções para tipos de instancia
    OPCOES_INSTANCIA = (
        ('E', 'Estadual'),
        ('F', 'Federal'),
        ('M', 'Municipal'),
    )
    
    nome = models.CharField(max_length=200, unique=True)
    responsavel = models.CharField(max_length=200, verbose_name="Responsável")
    cnpj = BRCNPJField(verbose_name='CNPJ')
    cep = BRPostalCodeField(verbose_name='CEP')
    rua = models.CharField(max_length=200, verbose_name="Logradouro")
    numero = models.CharField(max_length=10, verbose_name="Número")
    complemento = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2, choices=STATE_CHOICES, verbose_name='UF')
    pais = models.ForeignKey(CM_pais, on_delete=models.RESTRICT, verbose_name="País")
    telefone1 = models.CharField(max_length=20, verbose_name="Telefone", validators=[validate_national_phone_number])
    telefone2 = models.CharField(max_length=20, null=True, blank=True, verbose_name='Telefone secundário (opcional)', validators=[validate_national_phone_number])
    email = models.EmailField()
    instancia = models.CharField(max_length=10, choices=OPCOES_INSTANCIA, verbose_name="Tipo de instância")
    
    class Meta:
        verbose_name = 'SI - Mantenedor'
        verbose_name_plural = 'SI - Mantenedores'
        
    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        """Retorna a url para acessar uma instância de cm_pessoa"""
        return reverse('si_mantenedor-list')

class SI_ies(models.Model):
    """Armazena as IES: Instituto de Ensino Superior
    """
    nome = models.CharField(max_length=200)
    sigla = models.CharField(max_length=45)
    telefone1 = models.CharField(max_length=20)
    telefone2 = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField()
    
    class Meta:
        verbose_name = 'SI - IES'
        verbose_name_plural = "SI - IES"
        
    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        """Retorna a url para acessar uma instância de cm_polo"""
        return reverse('si_ies-list')

class CM_polo(models.Model):
    """Armazena os polos
    """
    OPCOES_STATUS = (
        ('A', 'Ativo'),
        ('C', 'Cancelado'),
        ('P', 'Publicado'),
        ('S', 'Suspenso'),
        ('E', 'Em análise'),
    )
    
    OPCOES_CLASSIFICACAO_SEED = (
        ('L', 'L - Polo com interrupção de entrada de estudantes nos cursos que necessitam de laboratório'),
        ('R', 'R - Polo com interrupção de entradas de estudantes'),
        ('S', 'S - Polo com infraestrutura suficiente'),
        ('T', 'T - Polo com recomendação de melhoria'),
    )
    
    DIAS_SEMANA = (
        ('dom', 'Domingo'),
        ('seg', 'Segunda'),
        ('ter', 'Terça'),
        ('qua', 'Quarta'),
        ('qui', 'Quinta'),
        ('sex', 'Sexta'),
        ('sab', 'Sábado'),
    )
    
    nome = models.CharField(max_length=45)
    mantenedor = models.ForeignKey(SI_mantenedor, on_delete=models.RESTRICT, null=True)
    status = models.CharField(max_length=1, choices=OPCOES_STATUS)
    coordenador = models.ForeignKey(CM_pessoa, null=True, on_delete=models.RESTRICT)
    telefone1 = models.CharField(max_length=20, verbose_name="Telefone")
    telefone2 = models.CharField(max_length=20, null=True, blank=True, verbose_name="Telefone opcional")
    email_institucional = models.EmailField()
    email_opcional = models.EmailField(null=True, blank=True)
    cep = BRPostalCodeField()
    rua = models.CharField(max_length=200, verbose_name="Logradouro")
    numero = models.CharField(max_length=10, verbose_name="Número")
    complemento = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2, choices=STATE_CHOICES)
    pais = models.ForeignKey(CM_pais, on_delete=models.RESTRICT, verbose_name="País")
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    classificacao_seed = models.CharField(max_length=500, null=True, blank=True, choices=OPCOES_CLASSIFICACAO_SEED, verbose_name="Classificação SEED")
    distancia_JF = models.PositiveIntegerField(null=True, blank=True, verbose_name="Distância do polo a Juiz de Fora", help_text="(Km)", validators=[validate_positive])
    tempo_viagem = models.CharField(max_length=45, null=True, blank=True, verbose_name="Tempo de viagem partindo de Juiz de Fora", help_text="hh:mm")
    dia_funcionamento_inicio = models.CharField(max_length=3, choices=DIAS_SEMANA, null=True, blank=True, verbose_name="Dia de funcionamento (início)")
    dia_funcionamento_fim = models.CharField(max_length=3, choices=DIAS_SEMANA, null=True, blank=True, verbose_name="Dia de funcionamento (fim)")
    horario_funcionamento_inicio = models.TimeField(null=True, blank=True, verbose_name="Horário de funcionamento (início)", help_text="hh:mm")
    horario_funcionamento_fim = models.TimeField(null=True, blank=True, verbose_name="Horário de funcionamento (fim)", help_text="hh:mm")
    apresentacao = models.TextField(null=True, blank=True, verbose_name="Apresentação")
    ies_vinculadas = models.ManyToManyField(SI_ies, verbose_name="IES vinculadas")
    
    class Meta:
        verbose_name = 'CM - Polo'
        
    def get_absolute_url(self):
        """Retorna a url para acessar uma instância de cm_polo"""
        return reverse('cm_polo-list')
    
    def __str__(self):
        return self.nome

Viagens/models.py
from django.db import models
from Acesso_Restrito.models import CM_pessoa

from procead.imports import *

from Curso.models import CM_curso

# Create your models here.
class VI_endereco(models.Model):
    nome = models.CharField(max_length=100)
    cep = models.CharField(max_length=10, verbose_name="CEP")
    rua = models.CharField(max_length=100, verbose_name="Logradouro")
    numero = models.PositiveIntegerField(verbose_name="Número")
    complemento = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2, choices=STATE_CHOICES, verbose_name="Estado")
    
    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'VI - Endereço'


class VI_os(models.Model):
    VI_STATUS_CHOICES = (
        ('A', 'Aprovado'),
        ('R', 'Reprovado'),
        ('P', 'Pendente')
    )
    
    viajante = models.ManyToManyField(CM_pessoa, verbose_name="Viajante(s)", help_text="Selecione um ou mais")
    solicitante = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT, related_name="coordenador")
    curso = models.ForeignKey(CM_curso, on_delete=models.RESTRICT)
    objetivo = models.TextField()
    justificativa = models.TextField()
    destino_ida = models.ForeignKey(VI_endereco, on_delete=models.RESTRICT, related_name="local_ida", verbose_name="Destino (ida)")
    data_ida = models.DateField(verbose_name="Data (ida)")
    horario_ida = models.TimeField(verbose_name="Horário (ida)", help_text="hh:mm")
    destino_volta = models.ForeignKey(VI_endereco, on_delete=models.RESTRICT, related_name="local_volta", verbose_name="Destino (volta)")
    data_volta = models.DateField(verbose_name="Data (volta)")
    horario_volta = models.TimeField(verbose_name="Horário (volta)", help_text="hh:mm")
    anexos = models.FileField(upload_to='upload', max_length=255, help_text='Espaço destinado à apresentação de documentos obrigatórios e acessórios à realização das viagens (justificativa formal, cronograma, folders, declarações diversas, etc)')
    status = models.CharField(max_length=1, choices=VI_STATUS_CHOICES, default='P', verbose_name='Alterar Status')

    def __str__(self):
        return str(self.id) + ' - ' + str(self.destino_ida) + ' - ' + str(self.data_ida) + ' - ' + str(self.curso)
    
    class Meta:
        verbose_name = 'VI - OS'
        verbose_name_plural = 'VI - OS'

Polo/views.py
from django import forms
from django.shortcuts import render
from Polo.filters import CM_poloFilter, SI_iesFilter, SI_mantenedorFilter
from Polo.forms import CM_poloForm, SI_associa_polo_iesForm
from Polo.models import CM_polo, SI_ies, SI_mantenedor

from procead.views import *

# Create your views here.
#Polo
@login_required(login_url='/accounts/login/')
def PoloView(request):
    return render(request, 'Polo/polo.html', {})

class CM_poloCreate(LoginRequiredMixin, CreateView):
    form_class = CM_poloForm
    template_name = 'Polo/cm_polo_form.html'

    def get_form(self, form_class=None):
        form = super(CM_poloCreate, self).get_form(form_class)
        form.fields['horario_funcionamento_inicio'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}))
        form.fields['horario_funcionamento_fim'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}))
        return form
    
class CM_poloUpdateView(LoginRequiredMixin, UpdateView):
    model = CM_polo
    form_class = CM_poloForm
    template_name = 'Polo/cm_polo_update.html'

class CM_poloListView(LoginRequiredMixin, ListView):
    model = CM_polo
    template_name = 'Polo/cm_polo_list.html'
    paginate_by = 15
    ordering = ['nome']
    
    def get_context_data(self, **kwargs):
        objects = CM_polo.objects.all().order_by('nome')
        filter = CM_poloFilter(self.request.GET, queryset=objects)
        
        paginator = Paginator(filter.qs, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['cm_polo_filter'] = filter
        context['page_obj'] = page_obj
        return context
    
class CM_poloDeleteView(LoginRequiredMixin, DeleteView):
    model = CM_polo
    template_name = 'Polo/cm_polo_delete.html'
    success_url = reverse_lazy('cm_polo-list')
    
class SI_associa_polo_iesUpdate(LoginRequiredMixin, UpdateView):
    model = CM_polo
    form_class = SI_associa_polo_iesForm
    template_name = 'Polo/si_associa_polo_ies_update.html'
    success_url = reverse_lazy('cm_polo-list')
       
class SI_mantenedorCreate(LoginRequiredMixin, CreateView):
    model = SI_mantenedor
    template_name = 'Polo/si_mantenedor_form.html'
    fields = '__all__'
    
    def get_form(self, form_class=None):
        form = super(SI_mantenedorCreate, self).get_form(form_class)
        form.fields['cnpj'].widget.attrs.update({'class': 'maskedCnpj'})
        form.fields['cep'].widget.attrs.update({'class': 'maskedCep'})
        form.fields['telefone1'].widget.attrs.update({'class': 'maskedPhoneBR'})
        form.fields['telefone2'].widget.attrs.update({'class': 'maskedPhoneBR'})
        return form

    def form_valid(self, form):
        messages.success(self.request, 'Mantenedor cadastrado com sucesso')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _(form.errors.as_data()))
        return super().form_valid(form)

        
class SI_mantenedorListView(LoginRequiredMixin, ListView):
    model = SI_mantenedor
    template_name = 'Polo/si_mantenedor_list.html'
    paginate_by = 15
    ordering = ['nome']
    
    def get_context_data(self, **kwargs):
        objects = SI_mantenedor.objects.all().order_by('nome')
        filter = SI_mantenedorFilter(self.request.GET, queryset=objects)
        
        paginator = Paginator(filter.qs, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['si_mantenedor_filter'] = filter
        context['page_obj'] = page_obj
        return context
    
class SI_mantenedorUpdateView(LoginRequiredMixin, UpdateView):
    model = SI_mantenedor
    template_name = 'Polo/si_mantenedor_update.html'
    fields = '__all__'
    
class SI_mantenedorDeleteView(LoginRequiredMixin, DeleteView):
    model = SI_mantenedor
    template_name = 'Polo/si_mantenedor_delete.html'
    success_url = reverse_lazy('si_mantenedor-list')

class SI_iesCreate(LoginRequiredMixin, CreateView):
    model = SI_ies
    template_name = 'Polo/si_ies_form.html'
    fields = '__all__'
    
    def get_form(self, form_class=None):
        form = super(SI_iesCreate, self).get_form(form_class)
        form.fields['telefone1'].widget.attrs.update({'class': 'maskedPhoneBR'})
        form.fields['telefone2'].widget.attrs.update({'class': 'maskedPhoneBR'})
        return form

class SI_iesListView(LoginRequiredMixin, ListView):
    model = SI_ies
    template_name = 'Polo/si_ies_list.html'
    paginate_by = 15
    ordering = ['nome']
    
    def get_context_data(self, **kwargs):
        objects = SI_ies.objects.all().order_by('nome')
        filter = SI_iesFilter(self.request.GET, queryset=objects)
        
        paginator = Paginator(filter.qs, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['si_ies_filter'] = filter
        context['page_obj'] = page_obj
        return context
    
class SI_iesUpdateView(LoginRequiredMixin, UpdateView):
    model = SI_ies
    template_name = 'Polo/si_ies_update.html'
    fields = '__all__'
    
class SI_iesDeleteView(LoginRequiredMixin, DeleteView):
    model = SI_ies
    template_name = 'Polo/si_ies_delete.html'
    success_url = reverse_lazy('si_ies-list')

Polo/templates/Polo/cm_polo_delete.html
{% extends "base_generic.html" %}

{% block content %}


{% include "includes/breadcrumb.html" with level=3 url2="polo" page2="Polo" current_page="Polos" %}
    
{% include "includes/delete_form.html" with title="Polos" divider="polo" name_url=cm_polo %}

{% endblock %}

Polo/templates/Polo/cm_polo_form.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="polo" page2="Polo" current_page="Polos" %}

<div class="container mb-5">
    
    {% include "includes/create_header.html" with title="Polos" divider="polo" list_url="cm_polo-list" %}
    
    {% include "includes/messages.html" %}

    <form method="post" action="">{% csrf_token %}
        <table class="table table-hover table-striped">
            {{ form.as_table }}
        </table>
        {{ form_si_associa_polo_ies.management_form }}    
        {% for extra_form in form_si_associa_polo_ies %}
        <div class="inlineForm" style="display: flex;">
            <span class="label">{{ extra_form.ies.label }}</span>
            <span class="poloSelect">{{ extra_form.ies }}</span>
        </div>
        {% endfor %}
        <br>
        
        {% include "includes/submit_button.html" with action="Cadastrar" %}
    </form>
</div>

{% include "includes/footer.html" %}

<script type="text/javascript">
    $(function() {
        $('.inlineForm').formset({
            prefix: '{{ form_si_associa_polo_ies.prefix }}',
            addText: 'Adicionar IES',
            deleteText: 'Remover IES'
        });
        $('#id_mantenedor').select2();
        $('#id_coordenador').select2();
        $('#id_uf').select2();
        $('#id_pais').select2().val(21).change();;

        $('#id_ies_vinculadas').addClass('overflow-auto h-100');

        $('#id_cep').on('change', async function(){
            const response = await fetch('https://viacep.com.br/ws/' + $('#id_cep').val().replace('-','') + '/json/');
            if(response.status == 200){
                var data = await response.json();
    
                $('#id_rua').val(data.logradouro);
                $('#id_complemento').val(data.complemento);
                $('#id_bairro').val(data.bairro);
                $('#id_uf').val(data.uf);
                $('#id_cidade').val(data.localidade);
                $('#id_uf').select2().val(data.uf).trigger('change');
            }
        })
    })
</script>

{% endblock %}

Polo/templates/Polo/cm_polo_update.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="polo" page2="Polo" current_page="Polos" %}

<div class="container">
    <h3 class="h3">Polos</h3>

    <div class="divider-polo mb-2"></div>

    <h4 class="h4">Polos: <strong>{{ instancia.nome }}</strong></h4>

    <form method="post" action="">{% csrf_token %}
        <table class="table table-hover table-striped">
            {{ form.as_table }}
        </table>
        {{ form_si_associa_polo_ies.management_form }}
        
        {% for extra_form in form_si_associa_polo_ies %}
        
        {% for hidden in extra_form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        
        <div class="inlineForm" style="display: flex;">
            <span class="label">{{ extra_form.ies.label }}</span>
            <span class="poloSelect">{{ extra_form.ies }}</span>
        </div>
        {% endfor %}
        <br>
        
        {% include "includes/submit_button.html" with action="Atualizar" %}

    </form>
</div>

<script type="text/javascript">
    $(function() {
        $('.inlineForm').formset({
            prefix: '{{ form_si_associa_polo_ies.prefix }}',
            addText: 'Adicionar IES',
            deleteText: 'Remover IES'
        });
    })
</script>

{% endblock %}

Polo/templates/Polo/polo.html
{% extends "base_generic.html" %}

{% block content %}
<main>
    {% include "includes/breadcrumb.html" with level=2 current_page="Polo" %}
    
    {% include "includes/submenu.html" with submenus=3 color="bg-polo" url1="cm_polo-list" page1="Polo" url2="si_ies-list" page2="IES (Instituição de Ensino Superior)" url3="si_mantenedor-list" page3="Mantenedor" %}
</main>
{% endblock %}

Polo/templates/Polo/si_ies_list.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="polo" page2="Polo" current_page="IES"%}

<div class="container">
    
    {% include "includes/list_header.html" with title="IES" divider="polo" create_url="si_ies-create"%}
    
    <div class="border-left border-right border-bottom">
        
        {% include "includes/list_filter.html" with filter_name=si_ies_filter.form.nome %}

        {% if si_ies_list %}
        <table id="list-table" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th class="text-center">Telefone</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Ver Mais</th>
                    <th class="text-center">Editar</th>
                    <th class="text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>
                {% for si_ies in page_obj %}
                <tr>
                    <td>{{si_ies.nome}}</td>
                    <td class="text-center">{{si_ies.telefone1}}</td>
                    <td class="text-center">{{si_ies.email}}</td>
                    <td class="text-center">
                        <a href="" data-bs-toggle="modal" data-bs-target="#iesModal{{si_ies.id}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'si_ies-update' si_ies.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ee844b" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'si_ies-delete' si_ies.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ae1f25" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
                            </svg>
                        </a>
                    </td>
                </tr>

                <!-- Modal contendo as informações do polo -->
                <div id="iesModal{{si_ies.id}}" class="modal fade" role="dialog">
                    <div class="modal-dialog modal-dialog-centered">
                  
                      <!-- Conteúdo do modal-->
                      <div class="modal-content">
                        <div class="bg-polo modal-header">
                            <h4 class="text-light modal-title">IES</h4>
                        </div>
                        <div class="modal-body">
                            <p><strong>Nome: </strong>{{si_ies.nome}}</p>
                            <p><strong>Sigla: </strong>{{si_ies.sigla}}</p>
                            <p><strong>Telefone: </strong>{{si_ies.telefone1}}</p>
                            {% if si_ies.telefone2 %}
                            <p><strong>Telefone Opcional: </strong>{{si_ies.telefone2}}</p>
                            {% endif %}
                            <p><strong>Email: </strong>{{si_ies.email}}</p>
                            {% if si_ies.cm_polo_set.all %}
                            <p><strong>Polos Associados:</strong></p>
                            <ul>
                                {% for polo in si_ies.cm_polo_set.all %}
                                <li>{{polo}}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                        </div>
                      </div>
                  
                    </div>
                  </div>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="ml-1 mt-3">Não há ofertas cadastradas no sistema</p>
        {% endif %}
        
        {% include "includes/pagination.html" %}
    </div>
</div>
{% endblock %}

Polo/templates/Polo/si_mantenedor_form.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="polo" page2="Polo" current_page="Mantenedor" %}

<div class="container">
    
    {% include "includes/create_header.html" with title="Mantenedor" divider="polo" list_url="si_mantenedor-list" %}
    
    {% include "includes/basic_form.html" %}
    
</div>

<script>
    $(function(){
        $('#id_uf').select2();
        $('#id_pais').select2().val(21).change();

        $('#id_cep').on('change', async function(){
            const response = await fetch('https://viacep.com.br/ws/' + $('#id_cep').val().replace('-','') + '/json/');
            if(response.status == 200){
                var data = await response.json();
    
                $('#id_rua').val(data.logradouro);
                $('#id_complemento').val(data.complemento);
                $('#id_bairro').val(data.bairro);
                $('#id_uf').val(data.uf);
                $('#id_cidade').val(data.localidade);
                $('#id_uf').select2().val(data.uf).trigger('change');
            }
        })
    })
</script>

{% endblock %}