Polo/urls.py
from django.urls import path

from Polo import views

urlpatterns = [
    path('', views.PoloView, name='polo'),
    
    path('polos/consulta', views.CM_poloListView.as_view(), name='cm_polo-list'),
    path('polos/cadastro', views.CM_poloCreate.as_view(), name='cm_polo-create'),
    path('polos/<int:pk>/editar', views.CM_poloUpdateView.as_view(), name='cm_polo-update'),
    path('polos/<int:pk>/excluir', views.CM_poloDeleteView.as_view(), name='cm_polo-delete'),
    path('polos/<int:pk>/associarPoloIes', views.SI_associa_polo_iesUpdate.as_view(), name='si_associa_polo_ies-update'),
    
    path('ies/consulta', views.SI_iesListView.as_view(), name='si_ies-list'),
    path('ies/cadastro', views.SI_iesCreate.as_view(), name='si_ies-create'),
    path('ies/<int:pk>/editar', views.SI_iesUpdateView.as_view(), name='si_ies-update'),
    path('ies/<int:pk>/excluir', views.SI_iesDeleteView.as_view(), name='si_ies-delete'),
    
    path('mantenedor/consulta', views.SI_mantenedorListView.as_view(), name='si_mantenedor-list'),
    path('mantenedor/cadastro', views.SI_mantenedorCreate.as_view(), name='si_mantenedor-create'),
    path('mantenedor/<int:pk>/editar', views.SI_mantenedorUpdateView.as_view(), name='si_mantenedor-update'),
    path('mantenedor/<int:pk>/excluir', views.SI_mantenedorDeleteView.as_view(), name='si_mantenedor-delete'),
]

Viagens/urls.py
from django.urls import path

from Viagens import views

urlpatterns = [
    path('', views.ViagemView, name='viagem'),
    path('endereco/consulta', views.VI_enderecoListView.as_view(), name='vi_endereco-list'),
    path('endereco/cadastro', views.VI_enderecoCreate.as_view(), name='vi_endereco-create'),
    path('endereco/<int:pk>/editar', views.VI_enderecoUpdateView.as_view(), name='vi_endereco-update'),
    path('endereco/<int:pk>/excluir', views.VI_enderecoDeleteView.as_view(), name='vi_endereco-delete'),
    path('os/consulta', views.VI_osListView, name='vi_os-list'),
    path('os/cadastro', views.VI_osCreate, name='vi_os-create'),
    path('os/<int:os_id>/editar', views.VI_osUpdateView, name="vi_os-update"),
    path('os/<int:pk>/excluir', views.VI_osDeleteView.as_view(), name="vi_os-delete"),    
    path('os/pendentes', views.VI_osPendentesListView.as_view(), name='vi_os_pendentes-list'),
    path('os/aprovados', views.VI_osAprovadosListView.as_view(), name='vi_os_aprovados-list'),
    path('os/reprovados', views.VI_osReprovadosListView.as_view(), name='vi_os_reprovados-list'),
    path('os/<int:pk>/aprovacao', views.VI_osAprovacao.as_view(), name='vi_os-aprovacao'),
]

proceg/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
# from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('procead/', include('procead.urls')),
    path('curso/', include('Curso.urls')),
    path('polo/', include('Polo.urls')),
    path('financeiro/', include('Financeiro.urls')),
    path('viagem/', include('Viagens.urls')),
    path('administracao/', include('Acesso_Restrito.urls')),
    path('curso/', include('Curso.urls')),
    path('almoxarifado/', include('Almoxarifado.urls')),
    path('ticket/', include('Ticket.urls')),
    path('', RedirectView.as_view(url='procead/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    ### Add Django site authentication urls (for login, logout, password management)
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

Viagens/models.py
from django.db import models
from Acesso_Restrito.models import CM_pessoa

from procead.imports import *

from Curso.models import CM_curso

# Create your models here.
class VI_endereco(models.Model):
    nome = models.CharField(max_length=100)
    cep = models.CharField(max_length=10, verbose_name="CEP")
    rua = models.CharField(max_length=100, verbose_name="Logradouro")
    numero = models.PositiveIntegerField(verbose_name="Número")
    complemento = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50)
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2, choices=STATE_CHOICES, verbose_name="Estado")
    
    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'VI - Endereço'


class VI_os(models.Model):
    VI_STATUS_CHOICES = (
        ('A', 'Aprovado'),
        ('R', 'Reprovado'),
        ('P', 'Pendente')
    )
    
    viajante = models.ManyToManyField(CM_pessoa, verbose_name="Viajante(s)", help_text="Selecione um ou mais")
    solicitante = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT, related_name="coordenador")
    curso = models.ForeignKey(CM_curso, on_delete=models.RESTRICT)
    objetivo = models.TextField()
    justificativa = models.TextField()
    destino_ida = models.ForeignKey(VI_endereco, on_delete=models.RESTRICT, related_name="local_ida", verbose_name="Destino (ida)")
    data_ida = models.DateField(verbose_name="Data (ida)")
    horario_ida = models.TimeField(verbose_name="Horário (ida)", help_text="hh:mm")
    destino_volta = models.ForeignKey(VI_endereco, on_delete=models.RESTRICT, related_name="local_volta", verbose_name="Destino (volta)")
    data_volta = models.DateField(verbose_name="Data (volta)")
    horario_volta = models.TimeField(verbose_name="Horário (volta)", help_text="hh:mm")
    anexos = models.FileField(upload_to='upload', max_length=255, help_text='Espaço destinado à apresentação de documentos obrigatórios e acessórios à realização das viagens (justificativa formal, cronograma, folders, declarações diversas, etc)')
    status = models.CharField(max_length=1, choices=VI_STATUS_CHOICES, default='P', verbose_name='Alterar Status')

    def __str__(self):
        return str(self.id) + ' - ' + str(self.destino_ida) + ' - ' + str(self.data_ida) + ' - ' + str(self.curso)
    
    class Meta:
        verbose_name = 'VI - OS'
        verbose_name_plural = 'VI - OS'

Viagens/forms.py
from django import forms
from Curso.models import CM_pessoa

from Viagens.models import VI_endereco, VI_os

class VI_enderecoForm(forms.ModelForm):
    class Meta:
        model = VI_endereco
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cep'].widget.attrs.update({'class': 'maskedCep'})
 
class VI_osForm(forms.ModelForm):   
    class Meta:
        model = VI_os
        fields = [  
            'viajante', 
            'curso',
            'objetivo',
            'justificativa',
            'destino_ida',
            'data_ida',
            'horario_ida',
            'destino_volta',
            'data_volta',
            'horario_volta',
            'anexos'
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['data_ida'] = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
        self.fields['data_volta'] = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
        self.fields['horario_ida'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}))
        self.fields['horario_volta'] = forms.TimeField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}))
        self.fields['viajante'].queryset = CM_pessoa.objects.order_by('nome').exclude(cpf='000.000.000-00')
        self.fields['anexos'].widget.attrs.update({'multiple': True})

Viagens/views.py
from django import forms
from django.shortcuts import render
from Acesso_Restrito.models import CM_pessoa
from Viagens.filters import VI_enderecoFilter
from Viagens.forms import VI_enderecoForm, VI_osForm
from Viagens.models import VI_endereco, VI_os

from procead.views import *

# Create your views here.
#Viagens
@login_required(login_url='/accounts/login/')
def ViagemView(request):
    return render(request, 'Viagem/viagem.html', {})

class VI_enderecoCreate(LoginRequiredMixin, CreateView):
    model = VI_endereco
    form_class = VI_enderecoForm
    template_name = 'Viagem/vi_endereco_form.html'
    
    def get_success_url(self):
        return reverse('vi_endereco-list')
    
class VI_enderecoListView(LoginRequiredMixin, ListView):
    model = VI_endereco
    template_name = 'Viagem/vi_endereco_list.html'
    paginate_by = 15
    
    def get_context_data(self, **kwargs):
        objects = VI_endereco.objects.all().order_by('nome')
        filter = VI_enderecoFilter(self.request.GET, queryset=objects)
        
        paginator = Paginator(filter.qs, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['vi_endereco_filter'] = filter
        context['page_obj'] = page_obj
        return context
    
class VI_enderecoUpdateView(LoginRequiredMixin, UpdateView):
    model = VI_endereco
    form_class = VI_enderecoForm
    template_name = 'Viagem/vi_endereco_update.html'
    
    def get_success_url(self):
        return reverse('vi_endereco-list')
    
class VI_enderecoDeleteView(LoginRequiredMixin, DeleteView):
    model = VI_endereco
    template_name = 'Viagem/vi_endereco_delete.html'
    
    def get_success_url(self):
        return reverse('vi_endereco-list')
   
@login_required(login_url='/accounts/login/')    
def VI_osCreate(request):
    if request.method == 'POST':
        form = VI_osForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['data_ida'] < date.today():
                messages.error(request, 'A data de saída precisa ser no futuro.')
            elif form.cleaned_data['data_ida'] > form.cleaned_data['data_volta']:
                messages.error(request, 'A data de retorno não pode ser anterior à data de saída.')
            elif form.cleaned_data['data_ida'] == form.cleaned_data['data_volta'] and form.cleaned_data['horario_ida'] > form.cleaned_data['horario_volta']:
                messages.error(request, 'O horário de partida na mesma data precisa ser inferior ao de retorno.')
            else:
                updated_form = form.save(commit=False)
                updated_form.solicitante = CM_pessoa.objects.filter(cpf=request.user.username).first()
                updated_form.save()
                os = VI_os.objects.last()
                os.viajante.set(form.cleaned_data['viajante'])
                os.save()
                return redirect('vi_os-list')
    form = VI_osForm()
    context = {
        'form': form
    }
    return render(request, 'Viagem/vi_os_form.html', context)

@login_required(login_url='/accounts/login/')    
def VI_osUpdateView(request, os_id):
    instance = VI_os.objects.filter(pk=os_id).first()
    if request.method == 'POST':
        form = VI_osForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            updated_form = form.save(commit=False)
            updated_form.solicitante = CM_pessoa.objects.filter(cpf=request.user.username).first()
            updated_form.save()
            instance.viajante.set(form.cleaned_data['viajante'])
            instance.save()
            return redirect('vi_os-list')
    form = VI_osForm(instance=instance)
    context = {
        'form': form
    }
    return render(request, 'Viagem/vi_os_update.html', context)

class VI_osDeleteView(LoginRequiredMixin, DeleteView):
    model = VI_os
    template_name = 'Viagem/vi_os_delete.html'
    
    def get_success_url(self):
        return reverse('vi_os-list')

class VI_osPendentesListView(LoginRequiredMixin, ListView):
    model = VI_os
    template_name = 'Viagem/vi_os_pendentes_list.html'
    paginate_by = 15
    
    def get_queryset(self):
        return VI_os.objects.filter(status='P')
    
    def get_context_data(self, **kwargs):
        objects = VI_os.objects.filter(status='P').order_by('-id')
        
        paginator = Paginator(objects, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['page_obj'] = page_obj
        return context

class VI_osAprovadosListView(LoginRequiredMixin, ListView):
    model = VI_os
    template_name = 'Viagem/vi_os_aprovados_list.html'
    paginate_by = 15
    
    def get_queryset(self):
        return VI_os.objects.filter(status='A')
    
    def get_context_data(self, **kwargs):
        objects = VI_os.objects.filter(status='A').order_by('-id')
        
        paginator = Paginator(objects, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['page_obj'] = page_obj
        return context
    
class VI_osReprovadosListView(LoginRequiredMixin, ListView):
    model = VI_os
    template_name = 'Viagem/vi_os_reprovados_list.html'
    paginate_by = 15
    
    def get_queryset(self):
        return VI_os.objects.filter(status='R')
    
    def get_context_data(self, **kwargs):
        objects = VI_os.objects.filter(status='R').order_by('-id')
        
        paginator = Paginator(objects, 15)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = super().get_context_data(**kwargs)
        
        context['page_obj'] = page_obj
        return context

class VI_osAprovacao(LoginRequiredMixin, UpdateView):
    model = VI_os
    fields = ['status']
    template_name = 'Viagem/vi_os_aprovacao.html'
    
    def get_context_data(self, **kwargs):
        os = self.object
        
        context = super().get_context_data(**kwargs)
        context['os'] = os
        return context
    
    def get_success_url(self):
        return reverse('vi_os_pendentes-list')

@login_required(login_url='/accounts/login/')    
def VI_osListView(request):
    solicitante = CM_pessoa.objects.filter(cpf=request.user.username).first()
    os_list = VI_os.objects.filter(solicitante=solicitante).order_by('-id')
    context = {
        'os_list': os_list,
        'solicitante': solicitante
    }
    return render(request, 'Viagem/vi_os_list.html', context)

Viagens/templates/Viagem/vi_endereco_delete.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagem" current_page="Cadastro de Endereços" %}
    
{% include "includes/delete_form.html" with title="Cadastro de Endereços" divider="viagem" name_url=vi_endereco %}

{% endblock %}

Viagens/templates/Viagem/vi_endereco_form.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagens" current_page="Cadastro de Endereços"%}

<div class="container">
    
    {% include "includes/create_header.html" with title="Cadastro de Endereços" divider="viagem" list_url="vi_endereco-list" %}
    
    {% include "includes/basic_form.html" %}
    
</div>

<script>
    $(document).ready(function(){
        $('#id_uf').select2();
    })

    $('#id_cep').on('change', async function(){
        const response = await fetch('https://viacep.com.br/ws/' + $('#id_cep').val().replace('-','') + '/json/');
        if(response.status == 200){
            var data = await response.json();

            $('#id_rua').val(data.logradouro);
            $('#id_complemento').val(data.complemento);
            $('#id_bairro').val(data.bairro);
            $('#id_uf').val(data.uf);
            $('#id_cidade').val(data.localidade);
            $('#id_uf').select2().val(data.uf).trigger('change');
        }
    })
</script>

{% endblock %}

Viagens/templates/Viagem/vi_endereco_update.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagens" current_page="Cadastro de Endereços" %}

<div class="container">
    {% include "includes/update_header.html" with title="Cadastro de Endereços" divider="viagem" subject=vi_endereco %}

    {% include "includes/update_form.html" %}
</div>

{% endblock %}

Viagens/templates/Viagem/vi_os_aprovados_list.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2='viagem' page2='Viagens' current_page='Autorizações' %}

<div class="container">
    <div class="d-flex gap-3 my-4">
        <a href="{% url 'vi_os_pendentes-list' %}" class="btn btn-gray"><span class="align-middle dot-pendentes me-2"></span>Pendentes</a>
        <a href="" class="btn btn-primary disabled"><span class="align-middle dot-aprovados me-2"></span>Aprovados</a>
        <a href="{% url 'vi_os_reprovados-list' %}" class="btn btn-gray"><span class="align-middle dot-reprovados me-2"></span>Reprovados</a>
    </div>

    {% if vi_os_list %}
        <table id="list-table" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Curso</th>
                    <th>Destino (ida)</th>
                    <th>Saída</th>
                    <th>Destino (volta)</th>
                    <th>Retorno</th>
                    <th class="text-center">Detalhes</th>
                </tr>
            </thead>
            <tbody>
                {% for os in page_obj %}
                <tr>
                    <td>{{os.id}}</td>
                    <td>{{os.curso}}</td>
                    <td>{{os.destino_ida}}</td>
                    <td>{{os.data_ida}}</td>
                    <td>{{os.destino_volta}}</td>
                    <td>{{os.data_volta}}</td>
                    <td class="text-center">
                        <a href="{% url "vi_os-aprovacao" os.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </a>
                    </td>
                </tr>

                <!-- Modal contendo as informações do polo -->
                <div id="osModal{{os.id}}" class="modal fade" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                  
                      <!-- Conteúdo do modal-->
                      <div class="modal-content">
                        <div class="bg-viagem modal-header">
                            <h4 class="text-light modal-title">Solicitação de viagem (id. {{os.id}})</h4>
                        </div>
                        <div class="modal-body">
                            <p><strong>Status: </strong>{{os.get_status_display}}</p>
                            <p><strong>Solicitante: </strong>{{os.solicitante}}</p>
                            <p><strong>Curso: </strong>{{os.curso.nome}}</p>
                            <p><strong>Passageiros:</strong></p>
                            <ul>
                                {% for passageiro in os.viajante.all %}
                                <li>{{passageiro}}</li>
                                {% endfor %}
                            </ul>
                            <p><strong>Destino (ida): </strong>{{os.destino_ida}}</p>
                            <p><strong>Horário (ida): </strong>{{os.data_ida}}, às {{os.horario_ida}}</p>
                            <hr>
                            <p><strong>Destino (volta): </strong>{{os.destino_volta}}</p>
                            <p><strong>Horário (volta): </strong>{{os.data_volta}}, às {{os.horario_volta}}</p>
                            <hr>
                            <p><strong>Objetivo: </strong>{{os.objetivo}}</p>
                            <p><strong>Justificativa: </strong>{{os.justificativa}}</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                        </div>
                      </div>
                  
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>

        {% include "includes/pagination.html" %}
        {% else %}
        <p class="ml-1 mt-3">Não há viagens aprovadas no sistema</p>
        {% endif %}
</div>

{% endblock %}

Viagens/templates/Viagem/vi_os_delete.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagem" current_page="Solicitação de Viagens" %}
    
{% include "includes/delete_form.html" with title="Solicitação de Viagens" divider="viagem" name_url=vi_os %}

{% endblock %}

Viagens/templates/Viagem/vi_os_form.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagens" current_page="Solicitação de Viagens"%}

<div class="container">
    <h3 class="h3 mt-5">Solicitação de Viagem</h3>

    <div class="divider-viagem mb-2"></div>

    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
    
        {% include "includes/messages.html" %}
        
        <table class="table table-hover table-striped">
            {{ form.as_table }}
        </table>
        
        {% include "includes/submit_button.html" with action="Cadastrar"%}
        
    </form>
</div>

<script type="text/javascript">
    $(function() {
        $('#id_viajante').select2();
        $('#id_curso').select2();
        $('#id_destino_ida').select2();
        $('#id_destino_volta').select2();
    })
</script>

{% endblock %}

Viagens/templates/Viagem/vi_os_pendentes_list.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2='viagem' page2='Viagens' current_page='Autorizações' %}

<div class="container">
    <div class="d-flex gap-3 my-4">
        <a href="" class="btn btn-primary disabled"><span class="align-middle dot-pendentes me-2"></span>Pendentes</a>
        <a href="{% url 'vi_os_aprovados-list' %}" class="btn btn-gray"><span class="align-middle dot-aprovados me-2"></span>Aprovados</a>
        <a href="{% url 'vi_os_reprovados-list' %}" class="btn btn-gray"><span class="align-middle dot-reprovados me-2"></span>Reprovados</a>
    </div>

    {% if vi_os_list %}
        <table id="list-table" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Curso</th>
                    <th>Destino (ida)</th>
                    <th>Saída</th>
                    <th>Destino (volta)</th>
                    <th>Retorno</th>
                    <th class="text-center">Detalhes</th>
                </tr>
            </thead>
            <tbody>
                {% for os in page_obj %}
                <tr>
                    <td>{{os.id}}</td>
                    <td>{{os.curso}}</td>
                    <td>{{os.destino_ida}}</td>
                    <td>{{os.data_ida}}</td>
                    <td>{{os.destino_volta}}</td>
                    <td>{{os.data_volta}}</td>
                    <td class="text-center">
                        <a href="{% url "vi_os-aprovacao" os.id %}" class="p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007bff" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </a>
                    </td>
                </tr>

                <!-- Modal contendo as informações do polo -->
                <div id="osModal{{os.id}}" class="modal fade" tabindex="-1" aria-labelledby="Modal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                  
                      <!-- Conteúdo do modal-->
                      <div class="modal-content">
                        <div class="bg-viagem modal-header">
                            <h4 class="text-light modal-title">Solicitação de viagem (id. {{os.id}})</h4>
                        </div>
                        <div class="modal-body">
                            <p><strong>Status: </strong>{{os.get_status_display}}</p>
                            <p><strong>Solicitante: </strong>{{os.solicitante}}</p>
                            <p><strong>Curso: </strong>{{os.curso.nome}}</p>
                            <p><strong>Passageiros:</strong></p>
                            <ul>
                                {% for passageiro in os.viajante.all %}
                                <li>{{passageiro}}</li>
                                {% endfor %}
                            </ul>
                            <p><strong>Destino (ida): </strong>{{os.destino_ida}}</p>
                            <p><strong>Horário (ida): </strong>{{os.data_ida}}, às {{os.horario_ida}}</p>
                            <hr>
                            <p><strong>Destino (volta): </strong>{{os.destino_volta}}</p>
                            <p><strong>Horário (volta): </strong>{{os.data_volta}}, às {{os.horario_volta}}</p>
                            <hr>
                            <p><strong>Objetivo: </strong>{{os.objetivo}}</p>
                            <p><strong>Justificativa: </strong>{{os.justificativa}}</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                        </div>
                      </div>
                  
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>

        {% include "includes/pagination.html" %}
        {% else %}
        <p class="ml-1 mt-3">Não há viagens pendentes no sistema</p>
        {% endif %}
</div>

{% endblock %}

Viagens/templates/Viagem/vi_os_update.html
{% extends "base_generic.html" %}

{% block content %}

{% include "includes/breadcrumb.html" with level=3 url2="viagem" page2="Viagens" current_page="Solicitação de Viagens"%}

<div class="container">
    <h3 class="h3 mt-5">Solicitação de Viagem</h3>

    <div class="divider-viagem mb-2"></div>

    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
    
        {% include "includes/messages.html" %}
        
        <table class="table table-hover table-striped">
            {{ form.as_table }}
        </table>
        
        {% include "includes/submit_button.html" with action="Cadastrar"%}
        
    </form>
</div>

<script type="text/javascript">
    $(function() {
        $('.inlineForm').formset({
            prefix: '{{ form_si_associa_polo_ies.prefix }}',
            addText: 'Adicionar IES',
            deleteText: 'Remover IES'
        });
        $('#id_viajante').select2();
        $('#id_curso').select2();
        $('#id_destino_ida').select2();
        $('#id_destino_volta').select2();
    })
</script>

{% endblock %}