Polo/urls.py
from django.urls import path

from Polo import views

urlpatterns = [
    path('', views.PoloView, name='polo'),
    
    path('polos/consulta', views.CM_poloListView.as_view(), name='cm_polo-list'),
    path('polos/cadastro', views.CM_poloCreate.as_view(), name='cm_polo-create'),
    path('polos/<int:pk>/editar', views.CM_poloUpdateView.as_view(), name='cm_polo-update'),
    path('polos/<int:pk>/excluir', views.CM_poloDeleteView.as_view(), name='cm_polo-delete'),
    path('polos/<int:pk>/associarPoloIes', views.SI_associa_polo_iesUpdate.as_view(), name='si_associa_polo_ies-update'),
    
    path('ies/consulta', views.SI_iesListView.as_view(), name='si_ies-list'),
    path('ies/cadastro', views.SI_iesCreate.as_view(), name='si_ies-create'),
    path('ies/<int:pk>/editar', views.SI_iesUpdateView.as_view(), name='si_ies-update'),
    path('ies/<int:pk>/excluir', views.SI_iesDeleteView.as_view(), name='si_ies-delete'),
    
    path('mantenedor/consulta', views.SI_mantenedorListView.as_view(), name='si_mantenedor-list'),
    path('mantenedor/cadastro', views.SI_mantenedorCreate.as_view(), name='si_mantenedor-create'),
    path('mantenedor/<int:pk>/editar', views.SI_mantenedorUpdateView.as_view(), name='si_mantenedor-update'),
    path('mantenedor/<int:pk>/excluir', views.SI_mantenedorDeleteView.as_view(), name='si_mantenedor-delete'),
]

Ticket/urls.py
from django.urls import path

from Ticket import views

urlpatterns = [
    path('', views.Solicitacoes, name='ticket'),
    path('solicitacao/consulta', views.SolicitacaoListView, name='ticket-list'),
    path('solicitacao/cadastro', views.SolicitacaoCreate, name='ticket-create'),
    path('solicitacao/<int:solicitacao_id>/edicao', views.SolicitacaoUpdateView, name='ticket-update'),
    path('solicitacao/<int:solicitacao_id>/assumir/<int:dev_id>', views.assumirSolicitacao, name='ticket-assumir'),
    path('solicitacao/<int:solicitacao_id>/encerrar/<int:dev_id>', views.encerrarSolicitacao, name='ticket-encerrar'),
    path('solicitacao/<int:solicitacao_id>/atualizar', views.atualizarSolicitacao, name='ticket-atualizar'),
    path('solicitacao/<int:solicitacao_id>/excluir', views.solicitacaoDeleteView, name='ticket-delete'),
    path('solicitacao/fechadas', views.FechadasListView, name='fechadas-list'),
    path('solicitacao/fechadas/consulta=<str:consulta>', views.FechadasListView, name='fechadas-list'),
    path('solicitacao/relatorios', views.solicitacaoRelatorio, name='ticket-relatorios'),
    path('solicitacao/relatorios/<str:intervalo>', views.solicitacaoRelatorio, name='ticket-relatorios'),
    path('solicitacao/relatorios/<str:consulta>', views.solicitacaoRelatorio, name='ticket-relatorios'),

    path('solicitacao/AVA', views.SolicitacaoAVA, name='ticket-ava'),
    path('solicitacao/AVA/disciplina/consulta', views.SolicitacaoDisciplinaListView, name='solicitacao-disciplina-list'),
    path('solicitacao/AVA/disciplina/cadastro', views.SolicitacaoDisciplinaCreate, name='solicitacao-disciplina-create'),
    path('solicitacao/AVA/disciplina/<int:solicitacao_id>/aprovacao_academico', views.SolicitacaoDisciplinaAprovacaoAcademico, name='solicitacao-disciplina-academico'),

    # Coloquei "course" de propósito. Favor não mudar.
    path('solicitacao/AVA/course/cadastro', views.SolicitacaoCursoCreate.as_view(), name='solicitacao-curso-create'),
    path('solicitacao/AVA/course/consulta', views.SolicitacaoCursoListView, name='solicitacao-curso-list'),
]

proceg/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
# from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('procead/', include('procead.urls')),
    path('curso/', include('Curso.urls')),
    path('polo/', include('Polo.urls')),
    path('financeiro/', include('Financeiro.urls')),
    path('viagem/', include('Viagens.urls')),
    path('administracao/', include('Acesso_Restrito.urls')),
    path('curso/', include('Curso.urls')),
    path('almoxarifado/', include('Almoxarifado.urls')),
    path('ticket/', include('Ticket.urls')),
    path('', RedirectView.as_view(url='procead/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    ### Add Django site authentication urls (for login, logout, password management)
        # accounts/login/ [name='login']
        # accounts/logout/ [name='logout']
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

Ticket/models.py
from tabnanny import verbose
from django.db import models
from django.forms import CharField
from Curso.models import CM_curso

from Acesso_Restrito.models import CM_pessoa

# Create your models here.
class Setor(models.Model):
    nome_setor = models.CharField(max_length=50, verbose_name="Nome do Setor")
    email = models.EmailField(verbose_name="E-mail do Setor")

    def __str__(self):
        return self.nome_setor

class Funcionario(models.Model):
    pessoa = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    setor = models.ForeignKey(Setor, on_delete=models.RESTRICT)
    is_coordenador = models.BooleanField(default=False, help_text = "Marque caso o funcionário seja coordenador do setor", verbose_name='Coordenadoria')

    def __str__(self):
        return self.pessoa.nome

    class Meta:
        verbose_name = 'Funcionário'


class Categoria(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Solicitacao(models.Model):
    STATUS_CHOICES = (
        ('A', 'Em aberto'),
        ('E', 'Em andamento'),
        ('F', 'Fechado'),
        ('P', 'Pendente'),
    )

    # ABERTURA
    data_abertura = models.DateTimeField(verbose_name="Data de Abertura", null=True, blank=True)
    solicitante = models.ForeignKey(Funcionario, on_delete=models.RESTRICT, verbose_name="Solicitante", null=True, blank=True)
    anexo = models.ImageField(upload_to='', blank=True, null=True)
    assunto = models.CharField(max_length=50)
    categoria = models.ForeignKey(Categoria, on_delete=models.RESTRICT)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="A")
    ultima_alteracao = models.DateTimeField(verbose_name="Última alteração", null=True, blank=True)
    
    # EM ANDAMENTO
    data_recebimento = models.DateTimeField(verbose_name="Data de Recebimento", null=True, blank=True)
    executante = models.ForeignKey(Funcionario, on_delete=models.RESTRICT, related_name="executante", null=True, blank=True)

    def __str__(self):
        return str(self.data_abertura.date()) + " - Assunto: " + self.assunto + " - Status: " + self.get_status_display()

    class Meta:
        verbose_name = 'Solicitação'
        verbose_name_plural = 'Solicitações'
class MensagemSolicitacao(models.Model):
    autor = models.ForeignKey(Funcionario, on_delete=models.RESTRICT, blank=True, null=True)
    data_mensagem = models.DateTimeField(blank=True, null=True)
    mensagem = models.TextField()
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.RESTRICT, blank=True, null=True)

    class Meta:
        verbose_name = "Mensagem - Solicitação"
        verbose_name_plural = "Mensagens - Solicitção"

    def __str__(self):
        return self.autor.pessoa.nome + " - " + str(self.data_mensagem)

TIPO_CURSO_CHOICES = (
    ('gra', 'Graduação'),
    ('esp', 'Especialização'),
    ('mes', 'Mestrado'),
    ('dou', 'Doutorado'),
    ('ext', 'Extensão'),
    ('cur', 'Curso Livre'),
)

STATUS_CHOICES = (
        ('A', 'Aberto'),
        ('E', 'Em Andamento'),
        ('P', 'Pendente'),
        ('F', 'Fechado')
    )

class SolicitacaoDisciplina(models.Model):
    solicitante = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    professor_responsavel = models.CharField(max_length=255, verbose_name="Professor Responsável")
    siape = models.CharField(max_length=7, verbose_name="SIAPE")
    email = models.EmailField(verbose_name="E-mail")
    CATEGORIA_CHOICES = (
        ('SIGA/UAB', 'Correspondência no SIGA/UAB'),
        ('SIGA/Flex', 'Correspondência no SIGA/Flexibilização Curricular'),
        ('Livre', 'Sem Correspondência no SIGA/Curso Livre')
    )
    categoria = models.CharField(max_length=9, choices=CATEGORIA_CHOICES)
    unidade_lotacao = models.CharField(max_length=50, verbose_name="Unidade de Lotação")
    codigo_siga = models.CharField(max_length=30, verbose_name="Código SIGA", blank=True, null=True)
    nome_disciplina = models.CharField(max_length=255, verbose_name="Nome da Disciplina")
    tipo_curso = models.CharField(max_length=3, choices=TIPO_CURSO_CHOICES, verbose_name="Tipo de Curso")
    curso_disciplina = models.ForeignKey(CM_curso, on_delete=models.RESTRICT, verbose_name="A qual curso pertence a disciplina")
    departamento_disciplina = models.CharField(max_length=255, verbose_name="A qual departamento pertence a disciplina")
    ano = models.CharField(max_length=4)
    semestre = models.CharField(max_length=1, choices=(('1','1'),('2','2'),('3','3'), ('4','4')))
    turma = models.CharField(max_length=12, verbose_name="Turmas pelas quais sou responsável")
    grupos = models.CharField(max_length=64, null=True, blank=True, verbose_name="Grupos (ex.: AB, C, ...)")
    conteudo_passado = models.CharField(max_length=255, null=True, blank=True, verbose_name="Favor informar o nome breve da disciplina a importar")
    MODO_INSCRICAO_ALUNOS_CHOICES = (
        ('ime', 'Imediatamente'),
        ('pos', 'Posteriormente'),
    )
    modo_inscricao_alunos = models.CharField(max_length=3, choices=MODO_INSCRICAO_ALUNOS_CHOICES, verbose_name="Alunos constantes naa FAE (SIGA) devem ser inscritos")
    atividades_inicio = models.DateField()
    atividades_fim = models.DateField()

    data_abertura = models.DateTimeField(blank=True, null=True)
    
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    ultima_atualizacao = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = "Solicitação de Disciplina"
        verbose_name_plural = "Solicitações de Disciplina"

class SolicitacaoCurso(models.Model):
    solicitante = models.ForeignKey(CM_pessoa, on_delete=models.RESTRICT)
    
    professor_responsavel = models.CharField(max_length=255, verbose_name="Professor Responsável")
    siape = models.CharField(max_length=7, verbose_name="SIAPE")
    unidade_lotacao = models.CharField(max_length=50, verbose_name="Unidade de Lotação")
    nome_curso = models.CharField(max_length=255, verbose_name="Nome do Curso")
    email = models.EmailField(verbose_name="E-mail")
    tipo_curso = models.CharField(max_length=3, choices=TIPO_CURSO_CHOICES, verbose_name="Tipo de Curso")
    CARACTERISTICAS_CHOICES = (
        ('UAB', 'UAB'),
        ('Não UAB', 'Não UAB'),
        ('ERE', 'ERE'),
        ('Híbrido', 'Híbrido'),
        ('Gratuito', 'Gratuito')
    )
    caracteristicas = models.CharField(max_length=8, choices=CARACTERISTICAS_CHOICES, verbose_name="Características")
    qtd_disciplinas = models.PositiveIntegerField(verbose_name="Quantidade de Disciplinas")
    inscricoes_inicio = models.DateField(verbose_name="Início das Inscrições")
    inscricoes_fim = models.DateField(verbose_name="Fim das Inscrições")
    curso_inicio = models.DateField(verbose_name="Início do Curso")
    curso_fim = models.DateField(verbose_name="Fim do Curso")
    # Quantidade de Interlocutores Envolvidos
    professores = models.PositiveIntegerField()
    tutores = models.PositiveIntegerField()
    demais_colaboradores = models.PositiveIntegerField()
    alunos = models.PositiveIntegerField()
    # Tipo de Demanda Requerida
    criacao_AVA = models.BooleanField(verbose_name="Criação de AVA", default=False, blank=True)
    matricula_alunos = models.BooleanField(verbose_name="Matrícula de Alunos", default=False, blank=True)
    capacitacao_interlocutores = models.BooleanField(verbose_name="Capacitação de Interlocutores", default=False, blank=True)
    outra = models.TextField(blank=True, null=True)
    producao_material = models.BooleanField(verbose_name="Acionamento do setor de produção de material do CEAD", default=False, blank=True)
    assessoria_comunicacao = models.BooleanField(verbose_name="Assessoria de comunicação para sua divulgação", default=False, blank=True)
    ambiente_pre_formatado = models.BooleanField(
        verbose_name="Seu curso/disciplina deseja ambiente pré formatado?", 
        help_text="O CEAD disponibiliza um Ambiente Modelo Pré Formatado para graduação e pós**",
        default=False, 
        blank=True)
    
    data_abertura = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    ultima_atualizacao = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return str(self.pk) + '. ' + self.nome_curso

    class Meta:
        verbose_name = "Solicitação de Curso"
        verbose_name_plural = "Solicitações de Curso"

Ticket/forms.py
from django import forms

from Ticket.models import MensagemSolicitacao, Solicitacao, SolicitacaoCurso, SolicitacaoDisciplina
from procead.models import SN
class SolicitacaoForm(forms.ModelForm):
    class Meta:
        model = Solicitacao
        fields = [
            'categoria',
            'assunto',
            'anexo',
            'data_abertura',
            'solicitante',
            'ultima_alteracao'
        ]

class MensagemSolicitacaoForm(forms.ModelForm):
    CHOICES = (
        ('P', 'Pendente'),
        ('F', 'Fechado')
    )
    
    status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, required=False, initial="F")
    encerrar = forms.BooleanField(required=False)
    class Meta:
        model = MensagemSolicitacao
        fields = [
            'autor',
            'data_mensagem',
            'mensagem',
            'solicitacao'
        ]

class RelatorioForm(forms.Form):
    data_inicio = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    data_fim = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

class SolicitacaoDisciplinaForm(forms.ModelForm):
    criar_grupos = forms.ChoiceField(choices=SN, label="As turmas devem ser separadas por grupos?", initial=0)
    importar_conteudo_passado = forms.BooleanField(label="É necessário importar conteúdo de períodos passados?", required=False)

    class Meta:
        model = SolicitacaoDisciplina
        fields = [
            'professor_responsavel',
            'email',
            'siape',
            'unidade_lotacao',
            'categoria',
            'codigo_siga',
            'ano',
            'semestre',
            'turma',
            'grupos',
            'nome_disciplina',
            'tipo_curso',
            'curso_disciplina',
            'departamento_disciplina',
            'conteudo_passado',
            'modo_inscricao_alunos',
            'atividades_inicio',
            'atividades_fim',
        ]

class SolicitacaoCursoForm(forms.ModelForm):
    class Meta:
        model = SolicitacaoCurso
        fields = [
            'professor_responsavel',
            'siape',
            'unidade_lotacao',
            'nome_curso',
            'tipo_curso',
            'caracteristicas',
            'qtd_disciplinas',
            'inscricoes_inicio',
            'inscricoes_fim',
            'curso_inicio',
            'curso_fim',
            'professores',
            'tutores',
            'demais_colaboradores',
            'alunos',
            'criacao_AVA',
            'matricula_alunos',
            'capacitacao_interlocutores',
            'outra',
            'producao_material',
            'assessoria_comunicacao',
            'ambiente_pre_formatado',
        ]
        widgets = {
            'outra': forms.TextInput(attrs={'placeholder': 'Especificar em caso de demanda adicional'}),
            'inscricoes_inicio': forms.widgets.DateInput(attrs={'type': 'date'}),
            'inscricoes_fim': forms.widgets.DateInput(attrs={'type': 'date'}),
            'curso_inicio': forms.widgets.DateInput(attrs={'type': 'date'}),
            'curso_fim': forms.widgets.DateInput(attrs={'type': 'date'}),
            'professores': forms.widgets.NumberInput(attrs={'class': 'num'}),
            'tutores': forms.widgets.NumberInput(attrs={'class': 'num'}),
            'demais_colaboradores': forms.widgets.NumberInput(attrs={'class': 'num'}),
            'alunos': forms.widgets.NumberInput(attrs={'class': 'num'}),
            'qtd_disciplinas': forms.widgets.NumberInput(attrs={'class': 'num'}),
        }

class SolicitacaoAprovacaoForm(forms.Form):
    aprovacao = forms.CharField()

Ticket/templates/Ticket/assumir_ticket.html
{% extends "base_generic.html" %}

{% block content %}

    {% include 'includes/breadcrumb.html' with level=4 page2="Solicitações" url2="ticket" page3="Lista de Solicitações" url3="ticket-list" current_page="Assumir Solicitação" %}

    <div class="container mt-5">
        <h3 class="h3">Solicitação número {{solicitacao.id}}:</h3>
        <h4 class="h4">{{solicitacao.assunto}}</h4>

        <div class="divider-ticket mb-2"></div>
        <p>Solicitação aberta em {{solicitacao.data_abertura}} por {{solicitacao.solicitante}} ({{solicitacao.solicitante.setor.nome_setor}})</p>
        
        <h5 class="h5">Categoria: {{solicitacao.get_categoria_display}}</h5>

        {% for mensagem in solicitacao.mensagemsolicitacao_set.all %}
        <div  class="textbox mt-3 p-2 {% if mensagem.autor == executante %}text-light ms-5 textboxAuthor{% else %}text-dark me-5 textboxOther{% endif %}">
            <div>
                <span><strong>{{mensagem.autor.pessoa.nome}}</strong></span>
            </div>
            <div>{{mensagem.mensagem}}</div>
            <div class="text-end">
                <span><small class="small">{{mensagem.data_mensagem}}</small></span>
            </div>
        </div>
        {% endfor %}

        {% if solicitacao.anexo %}
        <p>{{solicitacao.anexo}}</p>
        {% endif %}
        <form method="post" action="">{% csrf_token %}
            <div class="text-end">{{form.mensagem}}</div>

            <div class="text-end">
                {% include "includes/submit_button.html" with action="Enviar e Assumir" %}
            </div>
        </form>
    </div>
{% endblock %}

Ticket/templates/Ticket/atualizar_ticket.html
{% extends "base_generic.html" %}

{% block content %}

    {% include 'includes/breadcrumb.html' with level=4 page2="Solicitações" url2="ticket" page3="Lista de Solicitações" url3="ticket-list" current_page="Assumir Solicitação" %}

    <div class="container mt-5">
        <h3 class="h3">Solicitação número {{solicitacao.id}}:</h3>
        <h4 class="h4">{{solicitacao.assunto}}</h4>

        <div class="divider-ticket mb-2"></div>
        <p>Solicitação aberta em {{solicitacao.data_abertura}} por {{solicitacao.solicitante}} ({{solicitacao.solicitante.setor.nome_setor}})</p>
        
        <h5 class="h5">Categoria: {{solicitacao.get_categoria_display}}</h5>

        {% for mensagem in solicitacao.mensagemsolicitacao_set.all %}
        <div  class="textbox mt-3 p-2 {% if mensagem.autor == solicitante %}text-light ms-5 textboxAuthor{% else %}text-dark me-5 textboxOther{% endif %}">
            <div>
                <span><strong>{{mensagem.autor.pessoa.nome}}</strong></span>
            </div>
            <div>{{mensagem.mensagem}}</div>
            <div class="text-end">
                <span><small class="small">{{mensagem.data_mensagem}}</small></span>
            </div>
        </div>
        {% endfor %}

        {% if solicitacao.anexo %}
        <p>{{solicitacao.anexo}}</p>
        {% endif %}

        <form method="post" action="">{% csrf_token %}
            <div class="text-end">
                {{form.encerrar}}{{form.encerrar.label}}
            </div>
            
            <div class="text-end">{{form.mensagem}}</div>

            <div class="text-end">
                {% include "includes/submit_button.html" with action="Enviar e Atualizar" %}
            </div>
        </form>
    </div>
{% endblock %}

Ticket/templates/Ticket/encerrar_ticket.html
{% extends "base_generic.html" %}

{% block content %}

{% include 'includes/breadcrumb.html' with level=4 page2="Solicitações" url2="ticket" page3="Lista de Solicitações" url3="ticket-list" current_page="Assumir Solicitação" %}

<div class="container mt-5">
    <h3 class="h3">Solicitação número {{solicitacao.id}}:</h3>
    <h4 class="h4">{{solicitacao.assunto}}</h4>

    <div class="divider-ticket mb-2"></div>
    <p>Solicitação aberta em {{solicitacao.data_abertura}} por {{solicitacao.solicitante}} ({{solicitacao.solicitante.setor.nome_setor}})</p>
    
    <h5 class="h5">Categoria: {{solicitacao.get_categoria_display}}</h5>

    {% for mensagem in solicitacao.mensagemsolicitacao_set.all %}
    <div  class="textbox mt-3 p-2 {% if mensagem.autor == executante %}text-light ms-5 textboxAuthor{% else %}text-dark me-5 textboxOther{% endif %}">
        <div>
            <span><strong>{{mensagem.autor.pessoa.nome}}</strong></span>
        </div>
        <div>{{mensagem.mensagem}}</div>
        <div class="text-end">
            <span><small class="small">{{mensagem.data_mensagem}}</small></span>
        </div>
    </div>
    {% endfor %}

    {% if solicitacao.anexo %}
    <p>{{solicitacao.anexo}}</p>
    {% endif %}
    <form method="post" action="">{% csrf_token %}
        <div class="text-end">{{form.mensagem}}</div>

        <div class="text-end mt-2">
            <p>Escolha o novo status da solicitação:</p>
            {% for status in form.status %}
            <label class="mx-4">{{status}}</label>
            {% endfor %}
        </div>

        <div class="text-end">
            {% include "includes/submit_button.html" with action="Encerrar solicitação" %}
        </div>
    </form>
        
</div>

{% endblock %}

Ticket/templates/Ticket/solicitacao_academico.html
{% extends 'base_generic.html'%}

{% block content %}

{% include "includes/breadcrumb.html" with level=5 page2="Solicitações" url2="ticket" page3="Solicitações Ambiente Virtual de Aprendizagem" url3="ticket-ava" page4="Andamento das Solicitações de Disciplinas" url4="solicitacao-disciplina-list" current_page="Aprovação de Solicitação" %}

    <div class="container mt-5 w-75">
        <h3 class="h3">Informações para Abertura de AVA Moodle -  Disciplina - CEAD/PROGRAD</h3>
        <div class="divider-ticket mb-3"></div>
        
        <table class="table solicitacao-table">
            <tr>
                <td colspan="2"><strong>Professor Responsável: </strong>{{solicitacao.professor_responsavel}}</td>
                <td><strong>SIAPE: </strong>{{solicitacao.siape}}</td>
                <td><strong>Email: </strong>{{solicitacao.email}}</td>
            </tr>
            <tr>
                <td colspan="2"><strong>Nome da Disciplina: </strong>{{solicitacao.nome_disciplina}}</td>
                <td><strong>Departamento: </strong>{{solicitacao.departamento_disciplina}}</td>
                <td><strong>Unidade de Lotação: </strong>{{solicitacao.unidade_lotacao}}</td>
            </tr>
            <tr>
            {% if codigo_siga %}
                <td><strong>Código SIGA: </strong>{{solicitacao.codigo_siga}}</td>
                <td><strong>Ano/Semestre: </strong>{{solicitacao.ano}}/{{solicitacao.semestre}}</td>
                
            {% else %}
                <td colspan="2"><strong>Ano/Semestre: </strong>{{solicitacao.ano}}/{{solicitacao.semestre}}</td>
                
            {% endif %}
                
            {% if solicitacao.grupos %}
                <td><strong>Turma: </strong>{{solicitacao.turma}}</td>
                <td><strong>Grupos: </strong>{{solicitacao.grupos}}</td>
                
            {% else %}
                <td colspan="2"><strong>Turma: </strong>{{solicitacao.turma}}</td>
                
            {% endif %}
            </tr>
            <tr>

            </tr>
                <td><strong>Categoria: </strong>{{solicitacao.categoria}}</td>
            {% if solicitacao.conteudo_passado %}
                <td colspan="2"><strong>Cadastrar alunos: </strong>{{solicitacao.get_modo_inscricao_alunos_display}}</td>
                <td><strong>Importar conteúdo de: </strong>{{solicitacao.conteudo_passado}}</td>
            {% else %}
            <td colspan="3"><strong>Cadastrar alunos: </strong>{{solicitacao.get_modo_inscricao_alunos_display}}</td>
            {% endif %}

            <tr>
                <td colspan="2"><strong>Início das Atividades: </strong>{{solicitacao.atividades_inicio}}</td>
                <td colspan="2"><strong>Fim das Atividades: </strong>{{solicitacao.atividades_fim}}</td>
            </tr>
            <tr>
                <td colspan="4"><strong>Data de Abertura da Solicitação: </strong>{{solicitacao.data_abertura}}</td>
            </tr>
        </table>
        <form method="POST">{% csrf_token %}
            <div class="d-flex gap-3 w-50 mt-5">
                <input class="btn btn-primary w-25" type="submit" name="aprovacao" value="Aprovar">
                <input class="btn btn-warning w-25" type="submit" name="aprovacao" value="Reprovar">
                <button class="btn btn-secondary w-25" type="button">Cancelar</button>
            </div>
        </form>
    </div>

{% endblock %}

Ticket/templates/Ticket/ticket.html
{% extends "base_generic.html" %}

{% block content %}

    {% include "includes/breadcrumb.html" with level=2 current_page="Solicitações" %}

    {% include "includes/submenu.html" with page1="Abrir solicitação" url1="ticket-create" page2="Solicitações Ambiente Virtual de Aprendizagem" url2="ticket-ava" page3="Lista de Solicitações" url3="ticket-list" page4="Relatórios" url4="ticket-relatorios" %}

{% endblock %}

Ticket/templates/Ticket/ticket_AVA.html
{% extends "base_generic.html" %}

{% block content %}

    {% include "includes/breadcrumb.html" with level=3 page2="Solicitações" url2="ticket" current_page="Solicitações Ambiente Virtual de Aprendizagem" %}

    {% include "includes/submenu.html" with url1="solicitacao-curso-create" page1="Novo Curso" url2="solicitacao-disciplina-create" page2="Nova Disciplina" url4="solicitacao-disciplina-list" page4="Andamento das Solicitações de Disciplinas" url3="solicitacao-curso-list" page3="Andamento das Solicitações de Curso" %}

{% endblock %}